apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  template:
    spec:
      containers:
        - name: service
          image: xmlking/recorder-service:latest
          imagePullPolicy: Always
          ports:
            - name: grpc-port
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: env-vars
            - configMapRef:
                name: env-vars-common
            - secretRef:
                name: secrets
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 1
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 1
